export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/Oleg.Negruta/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
